# Generated by Django 6.0.1 on 2026-02-10 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statutProgramme', models.BooleanField(default=True)),
                ('dateProgramme', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeFonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fonction', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_fonction', models.CharField(choices=[('Actif', 'actif'), ('Bloque', 'bloque')], max_length=10)),
                ('user_fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typefonction')),
            ],
        ),
    ]
