# Generated by Django 6.0.1 on 2026-02-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='statutProgramme',
            field=models.CharField(default='ouii', max_length=10),
        ),
    ]
