# Generated by Django 6.0.1 on 2026-02-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_programme_statutprogramme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=80)),
                ('sexe', models.CharField(choices=[('Masculin', 'masculin'), ('Feminin', 'feminin')], max_length=15)),
                ('age', models.IntegerField()),
                ('adresse', models.CharField(max_length=100)),
                ('poids', models.IntegerField()),
                ('dateEn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
