# Generated by Django 6.0.1 on 2026-02-17 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_patient_phone_responsable_patient_userpatient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCummune', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stagiare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomStagiaires', models.CharField(max_length=80)),
                ('sexe', models.CharField(choices=[('Masculin', 'masculin'), ('Feminin', 'feminin')], max_length=20)),
                ('phone', models.IntegerField()),
                ('adresse', models.CharField(max_length=50)),
                ('type_stage', models.CharField(choices=[('Professionnel', 'professionnel'), ('Academique', 'academique')], max_length=30)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('stagiairename', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=150)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commune')),
                ('userStagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
