# Generated by Django 6.0.1 on 2026-02-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_commune_stagiare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='nomCummune',
            new_name='nomCommune',
        ),
        migrations.AddField(
            model_name='stagiare',
            name='dateRegistereStagiaire',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
