# Generated by Django 6.0.1 on 2026-03-15 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_nomcummune_commune_nomcommune_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='fonction',
            name='fonction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.typefonction'),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='user_fonction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fonction',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.service'),
        ),
    ]
