# Generated by Django 6.0.1 on 2026-03-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_service_alter_fonction_fonction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonction',
            name='adresse',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='fonction',
            name='etatCivil',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fonction',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='statut_fonction',
            field=models.CharField(choices=[('Actif', 'actif'), ('Bloque', 'bloque')], default='actif', max_length=10),
        ),
    ]
