# Generated by Django 6.0.1 on 2026-03-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_fonction_adresse_fonction_etatcivil_fonction_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonction',
            name='commune',
            field=models.CharField(choices=[('limete', 'Limete'), ('masina', 'Masina'), ('matete', 'Matete'), ('lemba', 'Lemba'), ("n'djili", "N'djili"), ('ngaliema', 'Ngaliema'), ('gombe', 'Gombe')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='etatCivil',
            field=models.CharField(choices=[('celibateur', 'Celibateur'), ('marie', 'Marie'), ('divorce', 'Divorce')], max_length=30, null=True),
        ),
    ]
