# Generated by Django 6.0.1 on 2026-03-17 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_fonction_commune_alter_fonction_etatcivil'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='commune',
            field=models.CharField(choices=[('limete', 'Limete'), ('masina', 'Masina'), ('matete', 'Matete'), ('lemba', 'Lemba'), ("n'djili", "N'djili"), ('ngaliema', 'Ngaliema'), ('gombe', 'Gombe')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='service_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.service'),
        ),
    ]
