# Generated by Django 6.0.1 on 2026-03-18 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_patient_commune_patient_service_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_a_payer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('est_soldee', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.prestation')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_verse', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('caissier', models.CharField(max_length=100)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='app.facture')),
            ],
        ),
    ]
