# Generated by Django 6.0.1 on 2026-03-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_prestation_alter_patient_options_facture_paiement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestation',
            old_name='prix',
            new_name='prix_fixe',
        ),
    ]
