# Generated by Django 6.0.1 on 2026-03-18 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_prix_prestation_prix_fixe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='est_soldee',
        ),
        migrations.AlterField(
            model_name='facture',
            name='prestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prestation'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_a_payer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
