# Generated by Django 6.0.1 on 2026-03-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_facture_est_soldee_alter_facture_prestation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_emission'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tension', models.CharField(blank=True, max_length=20, null=True)),
                ('statut', models.CharField(choices=[('TRIAGE', 'En attente Infirmerie'), ('DOCTEUR', 'En attente Médecin'), ('LABO', 'En attente Labo'), ('TERMINE', 'Terminé')], default='TRIAGE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('facture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.facture')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
    ]
