# Generated by Django 6.0.1 on 2026-03-19 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.service'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.facture'),
        ),
    ]
