# Generated by Django 6.0.1 on 2026-03-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_prestation_service_alter_consultation_facture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
