# Generated by Django 6.0.1 on 2026-03-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_facture_options_remove_paiement_caissier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='nom',
        ),
    ]
