# Generated by Django 6.0.1 on 2026-03-20 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_service_service_nom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fonction',
            name='commune',
        ),
        migrations.AddField(
            model_name='consultation',
            name='date_triage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='infirmier_triage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triages_effectues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pouls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='adresse',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='etatCivil',
            field=models.CharField(choices=[('celibateur', 'Célibataire'), ('marie', 'Marié'), ('divorce', 'Divorcé')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_responsable',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Stagiare',
        ),
    ]
