# Generated by Django 6.0.1 on 2026-03-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_fonction_commune_consultation_date_triage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='ordonnance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
