# Generated by Django 6.0.1 on 2026-03-22 12:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_categorie_materiel_mouvementstock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestation',
            options={'verbose_name': 'Prestation', 'verbose_name_plural': 'Prestations'},
        ),
        migrations.AddField(
            model_name='prestation',
            name='active',
            field=models.BooleanField(default=True, verbose_name='En vigueur'),
        ),
        migrations.AddField(
            model_name='prestation',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestation',
            name='est_fiche_obligatoire',
            field=models.BooleanField(default=False, help_text="Cochez cette case pour la prestation 'Fiche de consultation' unique.", verbose_name="Est la fiche d'entrée ?"),
        ),
        migrations.AddField(
            model_name='prestation',
            name='type_prestation',
            field=models.CharField(choices=[('GLOBAL', 'Général (Fiche, Dossier, Carte)'), ('SERVICE', 'Acte de Service (Consultation, Soin)'), ('EXTERNE', 'Prestation Externe')], default='SERVICE', max_length=10),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='libelle',
            field=models.CharField(max_length=150, verbose_name='Nom de la prestation'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='prix_fixe',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FC/$)'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestations', to='app.service', verbose_name='Service concerné'),
        ),
        migrations.AddConstraint(
            model_name='prestation',
            constraint=models.UniqueConstraint(condition=models.Q(('est_fiche_obligatoire', True)), fields=('est_fiche_obligatoire',), name='unique_fiche_obligatoire'),
        ),
    ]
