# Generated by Django 6.0.1 on 2026-03-22 13:24
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_prestation_options_prestation_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_emission'], 'verbose_name': 'Facture'},
        ),
        migrations.AddField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(
                choices=[('CASH', 'Espèces'), ('MOBILE', 'Mobile Money'), ('CARTE', 'Carte Bancaire')], 
                default='CASH', 
                max_length=10
            ),
        ),
        migrations.AlterField(
            model_name='facture',
            name='prestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.prestation'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_a_payer',
            # ICI : Correction de 'CASH' en 0 pour éviter l'erreur de nombre décimal
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]