# Generated by Django 6.0.1 on 2026-03-23 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_facture_options_paiement_mode_paiement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='diagnostic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_medecin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='paiement_examens_effectue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='total_a_payer_examens',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='statut',
            field=models.CharField(choices=[('TRIAGE', 'En attente Infirmerie'), ('DOCTEUR', 'En attente Médecin'), ('ATTENTE_PAIEMENT', 'En attente de Paiement (Caisse)'), ('LABO', 'En attente Labo'), ('TERMINE', 'Terminé')], default='TRIAGE', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_verse',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant perçu'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='service',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestations', to='app.service', verbose_name='Service concerné'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='examens_demandes',
            field=models.ManyToManyField(blank=True, related_name='consultations', to='app.examen'),
        ),
    ]
