# Generated by Django 6.0.1 on 2026-03-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_examen_consultation_diagnostic_consultation_medecin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='examens_demandes',
            field=models.ManyToManyField(blank=True, related_name='consultations_examens', to='app.prestation'),
        ),
    ]
