# Generated by Django 6.0.1 on 2026-03-23 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_consultation_examens_demandes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Consultation', 'verbose_name_plural': 'Consultations'},
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='facture',
        ),
        migrations.AddField(
            model_name='consultation',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='est_urgent',
            field=models.BooleanField(default=False, verbose_name='Marquer comme Urgence'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='message_urgence',
            field=models.TextField(blank=True, null=True, verbose_name='Note pour la réception'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='examens_demandes',
            field=models.ManyToManyField(blank=True, to='app.prestation'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='infirmier_triage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triages_infirmier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='app.patient'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='poids',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='pouls',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.service'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='statut',
            field=models.CharField(choices=[('TRIAGE', 'En attente de Triage'), ('DOCTEUR', 'Prêt pour Consultation'), ('LABO', 'Examens en cours'), ('ATTENTE_PAIEMENT', 'En attente de Paiement'), ('TERMINE', 'Consultation Terminée')], default='TRIAGE', max_length=30),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='temperature',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
