# Generated by Django 6.0.1 on 2026-03-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_consultation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={},
        ),
        migrations.AddField(
            model_name='consultation',
            name='reste_a_payer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consultation',
            name='somme_versee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='est_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='message_urgence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
