# Generated by Django 6.0.1 on 2026-03-23 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_consultation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_emission']},
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='mode_paiement',
        ),
        migrations.AddField(
            model_name='facture',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_consult', to='app.consultation'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='recepteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='total_a_payer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_verse',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
