# Generated by Django 6.0.1 on 2026-03-24 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_facture_total_a_payer_documenthospitalier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('MORGUE', 'Morgue'), ('PHARMACIE', 'Pharmacie'), ('LABO', 'Laboratoire')], max_length=50)),
                ('ref_objet', models.PositiveIntegerField()),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
