# Generated by Django 6.0.1 on 2026-03-25 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilleProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=100)),
                ('quantite_initiale', models.PositiveIntegerField()),
                ('quantite_actuelle', models.PositiveIntegerField()),
                ('prix_achat_unitaire_gros', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_peremption', models.DateField()),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('forme', models.CharField(max_length=50)),
                ('unite_gros', models.CharField(default='Boîte', max_length=20)),
                ('unite_detail', models.CharField(default='Comprimé', max_length=20)),
                ('coefficient', models.PositiveIntegerField(help_text='Nombre de détails dans 1 gros (ex: 30)')),
                ('prix_vente_gros', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_vente_detail', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_alerte_unites', models.PositiveIntegerField(default=10, help_text='Alerte en unités de détail')),
                ('famille', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.familleproduit')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouv', models.CharField(choices=[('VENTE_GROS', 'Vente en Gros'), ('VENTE_DETAIL', 'Vente au Détail'), ('ENTREE', 'Approvisionnement'), ('PERTE', 'Casse / Périmé')], max_length=20)),
                ('quantite', models.IntegerField(help_text='En unités de détail (comprimés)')),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='app.produit'),
        ),
    ]
