# Generated by Django 6.0.1 on 2026-03-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_familleproduit_lot_produit_mouvementpharmacie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='prix_achat_unitaire_gros',
        ),
        migrations.AddField(
            model_name='lot',
            name='prix_achat_total_lot',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix payé au fournisseur pour ce lot entier', max_digits=12),
            preserve_default=False,
        ),
    ]
